version: '3'

services:     
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: on-failure
    hostname: postgres
    networks:
      - cloud
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maindb
    volumes:
      - database:/var/lib/postgresql/data

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: 'app'
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_DOMAIN=postgres
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=maindb
    restart: on-failure
    tty: true
    networks:
      - cloud
    volumes:
      - $HOME/.m2:/root/.m2

volumes:
  database:
networks:
  cloud:
    name: cloud
    driver: bridge