version: '2'

services:
          
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: on-failure
    networks:
      - cloud
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=maindb

  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_DOMAIN=postgres
      - DATABASE_SCHEMA=maindb
    restart: on-failure
    tty: true
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - cloud
volumes:
  database:
networks:
  cloud:
    name: cloud
    driver: bridge