Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.provision "file", source: "demo", destination: "$HOME/demo"
    config.vm.provision "file", source: "Dockerfile", destination: "$HOME/"
    config.vm.provision "file", source: "docker-compose.yml", destination: "$HOME/"
    config.vm.provision "file", source: "nginx", destination: "$HOME/nginx"
    config.vm.network "forwarded_port", guest: 8080, host: 8085
    config.vm.provision :shell, path: "docker.sh"
    config.vm.provision :shell, path: "run_app.sh"

end