Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
  config.vm.provision "file", source: "demo", destination: "$HOME/"
  config.vm.provision "file", source: "Dockerfile", destination: "$HOME/"
  config.vm.provision :shell, path: "docker.sh"
  config.vm.provision :shell, path: "run_app.sh"

end